# Generated by Django 4.0.3 on 2022-04-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_alter_payment_expdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='court',
        ),
        migrations.AddField(
            model_name='comment',
            name='court_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
