# Generated by Django 4.0.3 on 2022-04-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_remove_comment_court_comment_court_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='court_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.court'),
        ),
    ]
