# Generated by Django 4.0.3 on 2022-04-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_alter_comment_court_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardnumber',
            field=models.CharField(max_length=25),
        ),
    ]
