# Generated by Django 4.0.3 on 2022-04-06 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0005_alter_payment_cardnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='court_id',
            new_name='court',
        ),
    ]
