# Generated by Django 4.0.3 on 2022-04-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0007_remove_comment_court_comment_court_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('game', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HSGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('game', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=255)),
            ],
        ),
    ]
